_wandb:
    value:
        cli_version: 0.21.2
        e:
            v8ju064q8gcd2usv7hhmx36aawxhruy5:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 32
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "12884901888"
                codePath: cs336_basics/train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "989436432384"
                email: me@zqzas.com
                executable: /Users/zsmbp/saas/cs336/assignment1-basics/.venv/bin/python3
                git:
                    commit: ec83e5e4b27835bcad71bce905400a2427732b99
                    remote: https://github.com/mhaowork/assignment1-basics
                host: zsmbpn-3.local
                memory:
                    total: "34359738368"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/zsmbp/saas/cs336/assignment1-basics/cs336_basics/train.py
                python: CPython 3.11.5
                root: /Users/zsmbp/saas/cs336/assignment1-basics/cs336_basics
                startedAt: "2025-11-22T00:53:05.011856Z"
                writerId: v8ju064q8gcd2usv7hhmx36aawxhruy5
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": val/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 7
                - 13
                - 16
                - 61
            "4": 3.11.5
            "5": 0.21.2
            "12": 0.21.2
            "13": darwin-arm64
batch_size:
    value: 32
context_length:
    value: 256
d_ff:
    value: 1536
d_model:
    value: 384
device:
    value: mps
learning_rate:
    value: 0.001
num_heads:
    value: 16
num_layers:
    value: 4
rope_theta:
    value: 10000
train_steps_per_epoch:
    value: 25
train_token_file:
    value: ../data/TinyStoriesV2-GPT4-train-tokens.txt
val_steps:
    value: 3
valid_token_file:
    value: ../data/TinyStoriesV2-GPT4-valid-tokens.txt
vocab_size:
    value: 50257
